### ISSUE TITLE
Is there a limit in stream MaxMessageSize?

### ISSUE THREAD

**Issue by TianshuDing** [0xfederama/bitcoin-simulation-libp2p#1]
in func handleStream(), when recevie the message from other peers, the "rw.Read()" return the messagelength and err. If other peers send a message above 4064, when the peer get the message, and unmarshal it, there is a error "unexpected end of json input". which means the message is not complete, something missing. so i give a big []byte to "rw.Read()", but still get the unmarshal err.
i think there must have some config to make handlestream get big file from other peers, do you have any idea?

**Comment by 0xfederama** [comment]
If you have big files to share on a network, I suggest you share them on a GossipSub (so it does everything automatically). Otherwise you have to choose a maximum length of the byte array to read (and you have to use the same size when sending the message). I think the best (and maybe only) way to send big files is to fragment them and send multiple messages.
Anyway, I'm not an expert, you should ask for it on [discuss.libp2p.io](discuss.libp2p.io)
